version: "3.9"

services:
  collaboration-dashboard:
    build: ./collaboration-dashboard
    container_name: collaboration-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./mock-api
    container_name: shibuya-demo-api
    ports:
      - "8000:8000"

