version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: shibuya-demo-frontend
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build: ./mock-api
    container_name: shibuya-demo-api
    expose:
      - "8081"

